In [1]:
import pandas as pd
import numpy as np

In [2]:
df_training = pd.read_csv("../Resources/training_set_features.csv")

In [3]:
df_labels = pd.read_csv("../Resources/training_set_labels.csv")

In [4]:
df = df_labels.merge(df_training, on = "respondent_id", how = "inner")

In [5]:
df.head()

respondent_id  h1n1_vaccine  seasonal_vaccine  h1n1_concern  \
0              0             0                 0           1.0   
1              1             0                 1           3.0   
2              2             0                 0           1.0   
3              3             0                 1           1.0   
4              4             0                 0           2.0   

   h1n1_knowledge  behavioral_antiviral_meds  behavioral_avoidance  \
0             0.0                        0.0                   0.0   
1             2.0                        0.0                   1.0   
2             1.0                        0.0                   1.0   
3             1.0                        0.0                   1.0   
4             1.0                        0.0                   1.0   

   behavioral_face_mask  behavioral_wash_hands  behavioral_large_gatherings  \
0                   0.0                    0.0                          0.0   
1                   0.0                    1.0                          0.0   
2                   0.0                    0.0                          0.0   
3                   0.0                    1.0                          1.0   
4                   0.0                    1.0                          1.0   

   ...             income_poverty  marital_status  rent_or_own  \
0  ...              Below Poverty     Not Married          Own   
1  ...              Below Poverty     Not Married         Rent   
2  ...  <= $75,000, Above Poverty     Not Married          Own   
3  ...              Below Poverty     Not Married         Rent   
4  ...  <= $75,000, Above Poverty         Married          Own   

    employment_status  hhs_geo_region                census_msa  \
0  Not in Labor Force        oxchjgsf                   Non-MSA   
1            Employed        bhuqouqj  MSA, Not Principle  City   
2            Employed        qufhixun  MSA, Not Principle  City   
3  Not in Labor Force        lrircsnp       MSA, Principle City   
4            Employed        qufhixun  MSA, Not Principle  City   

   household_adults  household_children  employment_industry  \
0               0.0                 0.0                  NaN   
1               0.0                 0.0             pxcmvdjn   
2               2.0                 0.0             rucpziij   
3               0.0                 0.0                  NaN   
4               1.0                 0.0             wxleyezf   

   employment_occupation  
0                    NaN  
1               xgwztkwe  
2               xtkaffoo  
3                    NaN  
4               emcorrxb  

[5 rows x 38 columns]

In [6]:
print(df.isnull().sum())

respondent_id                      0
h1n1_vaccine                       0
seasonal_vaccine                   0
h1n1_concern                      92
h1n1_knowledge                   116
behavioral_antiviral_meds         71
behavioral_avoidance             208
behavioral_face_mask              19
behavioral_wash_hands             42
behavioral_large_gatherings       87
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_h1n1                2160
doctor_recc_seasonal            2160
chronic_med_condition            971
child_under_6_months             820
health_worker                    804
health_insurance               12274
opinion_h1n1_vacc_effective      391
opinion_h1n1_risk                388
opinion_h1n1_sick_from_vacc      395
opinion_seas_vacc_effective      462
opinion_seas_risk                514
opinion_seas_sick_from_vacc      537
age_group                          0
education                       1407
race                               0
s

In [7]:
df1 = df.drop(["health_insurance","employment_industry", "employment_occupation"], axis=1)

In [8]:
print(df1.isnull().sum())


respondent_id                     0
h1n1_vaccine                      0
seasonal_vaccine                  0
h1n1_concern                     92
h1n1_knowledge                  116
behavioral_antiviral_meds        71
behavioral_avoidance            208
behavioral_face_mask             19
behavioral_wash_hands            42
behavioral_large_gatherings      87
behavioral_outside_home          82
behavioral_touch_face           128
doctor_recc_h1n1               2160
doctor_recc_seasonal           2160
chronic_med_condition           971
child_under_6_months            820
health_worker                   804
opinion_h1n1_vacc_effective     391
opinion_h1n1_risk               388
opinion_h1n1_sick_from_vacc     395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                      1407
race                              0
sex                               0
income_poverty              

In [9]:
df2 = df1.dropna()

In [10]:
df2.count()

respondent_id                  19642
h1n1_vaccine                   19642
seasonal_vaccine               19642
h1n1_concern                   19642
h1n1_knowledge                 19642
behavioral_antiviral_meds      19642
behavioral_avoidance           19642
behavioral_face_mask           19642
behavioral_wash_hands          19642
behavioral_large_gatherings    19642
behavioral_outside_home        19642
behavioral_touch_face          19642
doctor_recc_h1n1               19642
doctor_recc_seasonal           19642
chronic_med_condition          19642
child_under_6_months           19642
health_worker                  19642
opinion_h1n1_vacc_effective    19642
opinion_h1n1_risk              19642
opinion_h1n1_sick_from_vacc    19642
opinion_seas_vacc_effective    19642
opinion_seas_risk              19642
opinion_seas_sick_from_vacc    19642
age_group                      19642
education                      19642
race                           19642
sex                            19642
i

In [11]:
df2.shape

(19642, 35)

In [12]:
df2.dtypes

respondent_id                    int64
h1n1_vaccine                     int64
seasonal_vaccine                 int64
h1n1_concern                   float64
h1n1_knowledge                 float64
behavioral_antiviral_meds      float64
behavioral_avoidance           float64
behavioral_face_mask           float64
behavioral_wash_hands          float64
behavioral_large_gatherings    float64
behavioral_outside_home        float64
behavioral_touch_face          float64
doctor_recc_h1n1               float64
doctor_recc_seasonal           float64
chronic_med_condition          float64
child_under_6_months           float64
health_worker                  float64
opinion_h1n1_vacc_effective    float64
opinion_h1n1_risk              float64
opinion_h1n1_sick_from_vacc    float64
opinion_seas_vacc_effective    float64
opinion_seas_risk              float64
opinion_seas_sick_from_vacc    float64
age_group                       object
education                       object
race                     

In [13]:
df_y = df2.select_dtypes(include=['int64'])

In [14]:
df_y = df_y["h1n1_vaccine"]

In [15]:
df_y = np.array(df_y)

In [16]:
df_x = df2.drop(["respondent_id","h1n1_vaccine", "seasonal_vaccine"], axis=1)

In [17]:
df_x

h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0               1.0             0.0                        0.0   
1               3.0             2.0                        0.0   
3               1.0             1.0                        0.0   
4               2.0             1.0                        0.0   
5               3.0             1.0                        0.0   
...             ...             ...                        ...   
26700           3.0             1.0                        0.0   
26701           2.0             2.0                        0.0   
26702           2.0             0.0                        0.0   
26703           1.0             2.0                        0.0   
26706           0.0             0.0                        0.0   

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       0.0                   0.0                    0.0   
1                       1.0                   0.0                    1.0   
3                       1.0                   0.0                    1.0   
4                       1.0                   0.0                    1.0   
5                       1.0                   0.0                    1.0   
...                     ...                   ...                    ...   
26700                   1.0                   0.0                    1.0   
26701                   0.0                   0.0                    1.0   
26702                   1.0                   0.0                    0.0   
26703                   1.0                   0.0                    1.0   
26706                   1.0                   0.0                    0.0   

       behavioral_large_gatherings  behavioral_outside_home  \
0                              0.0                      1.0   
1                              0.0                      1.0   
3                              1.0                      0.0   
4                              1.0                      0.0   
5                              0.0                      0.0   
...                            ...                      ...   
26700                          0.0                      0.0   
26701                          0.0                      0.0   
26702                          0.0                      1.0   
26703                          0.0                      0.0   
26706                          0.0                      0.0   

       behavioral_touch_face  doctor_recc_h1n1  ...   race     sex  \
0                        1.0               0.0  ...  White  Female   
1                        1.0               0.0  ...  White    Male   
3                        0.0               0.0  ...  White  Female   
4                        1.0               0.0  ...  White  Female   
5                        1.0               0.0  ...  White    Male   
...                      ...               ...  ...    ...     ...   
26700                    1.0               1.0  ...  White  Female   
26701                    1.0               0.0  ...  White  Female   
26702                    0.0               0.0  ...  White  Female   
26703                    0.0               1.0  ...  White    Male   
26706                    0.0               0.0  ...  White    Male   

                  income_poverty  marital_status  rent_or_own  \
0                  Below Poverty     Not Married          Own   
1                  Below Poverty     Not Married         Rent   
3                  Below Poverty     Not Married         Rent   
4      <= $75,000, Above Poverty         Married          Own   
5      <= $75,000, Above Poverty         Married          Own   
...                          ...             ...          ...   
26700                  > $75,000         Married          Own   
26701                  > $75,000     Not Married         Rent   
26702  <= $75,000, Above Poverty     Not Married          Own   
26703  <= $75,000, Above Poverty     Not Married     

In [18]:
df_categories = df_x.select_dtypes(include=['object'])

In [19]:
df_float = df_x.select_dtypes(include=['float64'])

In [20]:
float_array = np.array(df_float)
float_array

array([[1., 0., 0., ..., 2., 0., 0.],
       [3., 2., 0., ..., 4., 0., 0.],
       [1., 1., 0., ..., 1., 0., 0.],
       ...,
       [2., 0., 0., ..., 2., 0., 0.],
       [1., 2., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [21]:
df_categories.head()

age_group     education   race     sex             income_poverty  \
0  55 - 64 Years    < 12 Years  White  Female              Below Poverty   
1  35 - 44 Years      12 Years  White    Male              Below Poverty   
3      65+ Years      12 Years  White  Female              Below Poverty   
4  45 - 54 Years  Some College  White  Female  <= $75,000, Above Poverty   
5      65+ Years      12 Years  White    Male  <= $75,000, Above Poverty   

  marital_status rent_or_own   employment_status hhs_geo_region  \
0    Not Married         Own  Not in Labor Force       oxchjgsf   
1    Not Married        Rent            Employed       bhuqouqj   
3    Not Married        Rent  Not in Labor Force       lrircsnp   
4        Married         Own            Employed       qufhixun   
5        Married         Own            Employed       atmpeygn   

                 census_msa  
0                   Non-MSA  
1  MSA, Not Principle  City  
3       MSA, Principle City  
4  MSA, Not Principle  City  
5       MSA, Principle City

In [22]:
features_array = np.array(df_categories)
features_array

array([['55 - 64 Years', '< 12 Years', 'White', ...,
        'Not in Labor Force', 'oxchjgsf', 'Non-MSA'],
       ['35 - 44 Years', '12 Years', 'White', ..., 'Employed',
        'bhuqouqj', 'MSA, Not Principle  City'],
       ['65+ Years', '12 Years', 'White', ..., 'Not in Labor Force',
        'lrircsnp', 'MSA, Principle City'],
       ...,
       ['65+ Years', 'Some College', 'White', ..., 'Not in Labor Force',
        'qufhixun', 'Non-MSA'],
       ['18 - 34 Years', 'College Graduate', 'White', ..., 'Employed',
        'lzgpxyit', 'MSA, Principle City'],
       ['65+ Years', 'Some College', 'White', ..., 'Not in Labor Force',
        'mlyzmhmf', 'MSA, Principle City']], dtype=object)

In [23]:

from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)

In [24]:
onehot = encoder.fit_transform(features_array)

In [25]:
onehot.shape

(19642, 38)

In [26]:
onehot

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [27]:
onehot[0]

array([0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1.])

In [28]:
df_features = np.concatenate((float_array, onehot),axis=1)
df_features

array([[1., 0., 0., ..., 0., 0., 1.],
       [3., 2., 0., ..., 1., 0., 0.],
       [1., 1., 0., ..., 0., 1., 0.],
       ...,
       [2., 0., 0., ..., 0., 0., 1.],
       [1., 2., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [29]:
df_features.shape

(19642, 60)

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(df_features, df_y, random_state=42)


In [32]:
from sklearn.preprocessing import MinMaxScaler

In [33]:
X_scaler1 = MinMaxScaler().fit(X_train)
X_train_scaled1 = X_scaler1.transform(X_train)
X_test_scaled1 = X_scaler1.transform(X_test)

In [34]:
X_train_scaled1[0]

array([0.66666667, 1.        , 0.        , 1.        , 1.        ,
       1.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 1.        , 0.        , 0.        , 0.75      ,
       0.25      , 0.25      , 0.75      , 0.25      , 1.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       1.        , 0.        , 0.        , 1.        , 0.        ,
       1.        , 0.        , 0.        , 1.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ])

In [52]:
# Support vector machine linear classifier
from sklearn.svm import SVC 
model = SVC(kernel='linear')
model.fit(X_train_scaled1, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [53]:
features_training_score = round((model.score(X_train_scaled1, y_train))*100,3) 
features_accuracy = round((model.score(X_test_scaled1, y_test))*100,3)
print(f"Training Data Score: {features_training_score}%")
print(f"Testing Data Score: {features_accuracy}%")

Training Data Score: 83.104%
Testing Data Score: 82.325%


In [55]:
#gridsearch
model1 = SVC(kernel='linear')
model1

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [58]:
# Create the GridSearch estimator along with a parameter object containing the values to adjust
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10, 50],
              'gamma': [0.0001, 0.0005, 0.001, 0.005]}
grid = GridSearchCV(model1, param_grid, verbose=3, cv=5)

In [59]:
# Fit the model using the grid search estimator. 
# This will take the SVC model and try each combination of parameters
grid.fit(X_train_scaled1, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] C=1, gamma=0.0001 ...............................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ................... C=1, gamma=0.0001, score=0.830, total=   6.9s
[CV] C=1, gamma=0.0001 ...............................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.8s remaining:    0.0s


[CV] ................... C=1, gamma=0.0001, score=0.827, total=   6.8s
[CV] C=1, gamma=0.0001 ...............................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   13.6s remaining:    0.0s


[CV] ................... C=1, gamma=0.0001, score=0.827, total=   6.7s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.837, total=   6.9s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.827, total=   6.7s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ................... C=1, gamma=0.0005, score=0.830, total=   6.8s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ................... C=1, gamma=0.0005, score=0.827, total=   6.7s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ................... C=1, gamma=0.0005, score=0.827, total=   6.7s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ................... C=1, gamma=0.0005, score=0.837, total=   6.8s
[CV] C=1, gamma=0.0005 ...............................................
[CV] .

[CV] .................. C=50, gamma=0.0001, score=0.830, total= 1.5min
[CV] C=50, gamma=0.0001 ..............................................
[CV] .................. C=50, gamma=0.0001, score=0.827, total= 1.5min
[CV] C=50, gamma=0.0001 ..............................................
[CV] .................. C=50, gamma=0.0001, score=0.826, total= 1.5min
[CV] C=50, gamma=0.0001 ..............................................
[CV] .................. C=50, gamma=0.0001, score=0.837, total= 1.5min
[CV] C=50, gamma=0.0001 ..............................................
[CV] .................. C=50, gamma=0.0001, score=0.827, total= 2.8min
[CV] C=50, gamma=0.0005 ..............................................
[CV] .................. C=50, gamma=0.0005, score=0.830, total= 1.6min
[CV] C=50, gamma=0.0005 ..............................................
[CV] .................. C=50, gamma=0.0005, score=0.827, total= 1.7min
[CV] C=50, gamma=0.0005 ..............................................
[CV] .

[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed: 48.6min finished


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='linear',
                           max_iter=-1, probability=False, random_state=None,
                           shrinking=True, tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [1, 5, 10, 50],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [60]:
# List the best parameters for this dataset
print(grid.best_params_)

{'C': 10, 'gamma': 0.0001}


In [61]:
# List the best score
print(grid.best_score_)

0.829475256262304


In [62]:

tuned_training_score = round((grid.score(X_train_scaled1, y_train))*100,3)
tuned_accuracy = round((grid.score(X_test_scaled1, y_test))*100,3)

print(f"Training Data Score: {tuned_training_score}%")
print(f"Testing Data Score: {tuned_accuracy}%")

Training Data Score: 83.11%
Testing Data Score: 82.346%


In [64]:
#Predictions for tuned model
predictions = grid.predict(X_test_scaled1)
classifications = y_test.tolist()

predicted = {
    'Actual': y_test,
    'Prediction': predictions
}

prediction_df = pd.DataFrame(predicted)
prediction_df = prediction_df.set_index('Actual').reset_index()
prediction_df.head(15)

Actual  Prediction
0        0           0
1        0           0
2        0           0
3        0           0
4        0           0
5        0           0
6        0           0
7        0           0
8        1           1
9        0           0
10       0           0
11       0           0
12       1           1
13       0           0
14       0           0

In [65]:
import joblib

filename = 'SMV_grid.sav'
joblib.dump(grid, filename)

['SMV_grid.sav']